name: SharkClock
version: 1.0
Author: Numixe & GiantRaven
main: it.sharkcraft.sharkclock.SharkClock
commands:
    shtime:
        description: View time
    shdate:
        description: View date
    clock:
        aliases: [clock info]
        usage: |
            Use /help clock [subcommand] for more information
            /clock info - Show clock information
            /clock start - Start clock
            /clock stop - Stop clock
            /clock update - Update clock when stopped
            /clock set [digit] [index] - Set block for a digit to an index
            /clock add [digit] - Add block for a digit
            /clock remove [digit] [index] - Remove block for a digit to an index
            /clock position [arg] [digitID] - Set the clock location 
            /clock save - Save config.yml and reload clock settings
            /clock shdigit [digit] - Show all blocks of a digit
            /clock shpos [arg] [digitID] - Show the position
            /clock setvolume - Set a block list delimite by a volume
        description: Alias to clock status
    clock start:
        description: Start clock
        usage: /clock start
    clock stop:
        description: Stop clock
        usage: /clock stop
    clock update:
        description: Update clock when stopped
        usage: /clock update
    clock set:
        description: Set an existing block
        usage: |
            Use /clock set <digit> <indexnumber>
            then touch the block
            warning - <indexnumber> starts by 0
    clock add:
        description: Register a new block
        usage: |
            Use /clock add <digit>
            then touch the block
    clock remove:
        description: Remove an existing block
        alias: [clock rm]
        usage: |
            Use /clock remove <digit> <indexnumber>
            warning - <indexnumber> starts by 0
    clock position:
        description: Set the position of the digit with a relative type
        alias: [clock pos]
        usage: |
            Use /clock position <type> <digit>
            <type> - = { hours, h }
                     = { minutes, min }
                     = { seconds, sec }
            <digit> - = { first, f, 1 }
                      = { second, s, 2 }
    clock save:
        description: Save and reload config.yml
        usage: |
            Use /clock save
    clock shdigit:
        description: Show all blocks of a digit
        usage: |
            Use /clock shdigit <digit>
            warning - <indexnumber> starts by 0
    clock shpos:
        description: Show the position at the given arguments
        usage: |
            Use /clock shpos <type> <digitID>
            <type> - = { hours, h }
                     = { minutes, min }
                     = { seconds, sec }
            <digit> - = { first, f, 1 }
                      = { second, s, 2 }
    clock setvolume:
        description: Set a block list delimite by a volume
        usage: |
            Use /clock setvolume <digit>
            warning - <digit> starts by 0

