name: SharkClock
version: 1.0
Author: Numixe & GiantRaven
main: it.sharkcraft.sharkclock.SharkClock
commands:
    shtime:
        description: View time
    shdate:
        description: View date
    clock:
        aliases: [clock info]
        usage: |
            Use /help clock [subcommand] for more information
            /clock info - Show clock information
            /clock start - Start clock
            /clock stop - Stop clock
            /clock update - Update clock when stopped
        description: Alias to clock status
    clock start:
        description: Start clock
        usage: /clock start
    clock stop:
        description: Stop clock
        usage: /clock stop
    clock update:
        description: Update clock when stopped
        usage: /clock update
    clock set:
        description: Set an existing block
        usage: Syntax |
                   /clock set <digit> <indexnumber>
               then touch the block
               warning - <indexnumber> starts by 0
   clock add:
        description: Register a new block
        usage: Syntax |
                   /clock add <digit>
               then touch the block
   clock remove:
        description: Remove an existing block
        alias: [clock rm]
        usage: Syntax |
                   /clock remove <digit> <indexnumber>
               warning - <indexnumber> starts by 0
   clock position:
        description: Set the position of the digit with a relative type
        alias: [clock pos]
        usage: Syntax |
                   /clock position <type> <digit>
               <type> - = { hours, h }
                        = { minutes, min }
                        = { seconds, sec }
               <digit> - = { first, f, 1 }
                         = { second, s, 2 } 
